# Generated by Django 5.2.7 on 2025-11-03 20:42

import django.db.models.deletion
import market.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=market.models.vehicle_image_path),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="vehiclephoto",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="ad_type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="featured_until",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="has_document",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="is_drivable",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="issues",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="user",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Carroceria"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=30, verbose_name="Cor"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel",
            field=models.CharField(
                choices=[
                    ("flex", "Flex"),
                    ("gasolina", "Gasolina"),
                    ("etanol", "Etanol"),
                    ("diesel", "Diesel"),
                    ("eletrico", "Elétrico"),
                    ("hibrido", "Híbrido"),
                ],
                default="flex",
                max_length=12,
                verbose_name="Combustível",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="gearbox",
            field=models.CharField(
                choices=[("manual", "Manual"), ("auto", "Automático"), ("cvt", "CVT")],
                default="manual",
                max_length=10,
                verbose_name="Câmbio",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Publicado"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="repass",
            field=models.BooleanField(default=False, verbose_name="É repasse?"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="version",
            field=models.CharField(blank=True, max_length=80, verbose_name="Versão"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(max_length=50, verbose_name="Marca"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="city",
            field=models.CharField(max_length=60, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.PositiveIntegerField(verbose_name="Quilometragem (km)"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(max_length=80, verbose_name="Modelo"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="state",
            field=models.CharField(max_length=2, verbose_name="UF"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Título curto"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Ano"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["slug"], name="market_vehi_slug_d52b7e_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["brand", "model", "year"], name="market_vehi_brand_934a66_idx"
            ),
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="market.vehicle",
            ),
        ),
        migrations.DeleteModel(
            name="VehiclePhoto",
        ),
    ]
