# Generated by Django 5.2.7 on 2025-11-05 16:47

import django.core.validators
import django.utils.timezone
import market.models
import market.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_vehicle_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vehicleimage",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="market_vehi_slug_d52b7e_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="market_vehi_brand_934a66_idx",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="body_type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="color",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="fuel",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="gearbox",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="repass",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="title",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="version",
        ),
        migrations.RemoveField(
            model_name="vehicleimage",
            name="order",
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="is_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="city",
            field=models.CharField(db_index=True, max_length=80, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quilometragem (km)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="state",
            field=models.CharField(
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                db_index=True,
                max_length=2,
                verbose_name="UF",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="image",
            field=models.ImageField(
                upload_to=market.models.vehicle_image_path,
                validators=[market.utils.images.validate_image],
            ),
        ),
    ]
