# Generated by Django 5.2.7 on 2025-11-05 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_alter_vehicle_options_alter_vehicleimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="mileage",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quilometragem (km)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Preço (R$)",
            ),
        ),
    ]
